### ISSUE TITLE
Navbar login button is hidden at certain screen sizes

### ISSUE THREAD

**Issue by jakegrella** [iron-fish/website#166]
The login button in the navbar becomes hidden between the md (768px) and lg (1024px) breakpoints.

I tried to fix this in [`Navbar/index.js`](https://github.com/iron-fish/website/blob/0b7fcb60ebe585297d12c25ae478a7a202b685b1/src/theme/Navbar/index.js#L92) but don't know enough about Tailwind. Seems like the quickest fix would be

```diff
// line 92
- <div className="hidden md:flex items-center lg:text-xl">
+ <div className="hidden lg:flex items-center lg:text-xl">
```
```diff
// line 99
- className={`md:hidden ${overrides.button} ${overrides.menuButton}`}
+ className={`lg:hidden ${overrides.button} ${overrides.menuButton}`}
```
Unfortunately, that doesn't seem to work. In tailwind.config.js I see that both `md` and `lg` are commented out, but I'm not sure if that has anything to do with it, and that's as far as I was able to get.

![Screen Shot 2022-05-05 at 9 34 07 PM](https://user-images.githubusercontent.com/17218775/167057528-a8802199-0a06-4c1b-b4ed-82ff3bb5716c.png)
![Screen Shot 2022-05-05 at 9 33 04 PM](https://user-images.githubusercontent.com/17218775/167057595-19b86458-aa48-4ac3-bdc4-81b7d5cf3edd.png)

**Comment by lwisne** [comment]
This kind of thing can be annoying to fix without breaknig something else. Will need to take care.

**Comment by dguenther** [comment]
The website has been redesigned, so this has been addressed.
