### ISSUE TITLE
Whitepaper consists of private google doc link

### ISSUE THREAD

**Issue by wd021** [iron-fish/website#181]
On [account creation page](https://github.com/iron-fish/website/blob/master/docs/whitepaper/5_account.md), the section

> The Authorization Key (ak) is derived as the public key for the spend authorization key by multiplying the spend authorizing key with a fixed generator base point for it on the [Jubjub curve](https://docs.google.com/document/d/14KRwTuWNnLM6sKbItjB8agFaATDj02rktFBArpB92vI/edit#heading=h.z72856p4jl5q).

links to a google doc that requires permission to access

**Comment by gitakileus** [comment]
Hello 
I saw this Figma design https://www.figma.com/file/E04zlsQJHbywfHq7zGqwt1/Testnet-Rewards-Page?node-id=315%3A65 in your job posting.
And I saw this and complete test site within 3 hours
please check this https://glittery-speculoos-31b8b5.netlify.app/
I hope I can contribute to this iron fish.
I will do all the best for this.

**Comment by deekerno** [comment]
This has been rectified through #190. Thanks for catching this!
