### ISSUE TITLE
Text issues in Installation page

### ISSUE THREAD

**Issue by hamza-siddiq** [iron-fish/website#192]
I found a few documentation issues in the installation page, found under get started page on the ironfish website. Just some spelling and grammar fixes. There are three spelling and grammar issues, which I have pasted below:

1. Here the text should read: update "them" through
<img width="628" alt="Screen Shot 2022-08-16 at 12 06 25 AM" src="https://user-images.githubusercontent.com/92462002/184700334-29b44b81-e934-43d8-8234-48abd9c10414.png">

 2. "the" is repeated twice, the second one is unnecessary, and hence should be removed
<img width="863" alt="Screen Shot 2022-08-16 at 12 05 57 AM" src="https://user-images.githubusercontent.com/92462002/184700367-e79b9b39-f71c-4a7a-9cec-74d3501ea9db.png">

3. Here it should be: from "the" source
<img width="876" alt="Screen Shot 2022-08-16 at 12 01 26 AM" src="https://user-images.githubusercontent.com/92462002/184699787-a61fe10b-3aa8-4ef7-9f88-993e6d2df8ef.png">

**Comment by lwisne** [comment]
you can fix the double "the" typo in the second example if you would like. The other two are not wrong.
