### ISSUE TITLE
Center align the thank you subscription text

### ISSUE THREAD

**Issue by hamza-siddiq** [iron-fish/website#197]
A small text alignment issue that I found. The text "Thank you for subscribing!" should be aligned in the center, which would look better.

Will work on this if accepted.

<img width="1439" alt="Screen Shot 2022-08-17 at 2 46 03 PM" src="https://user-images.githubusercontent.com/92462002/185189526-68c9d0b2-425e-4879-825b-dc442eec81a9.png">

**Comment by dguenther** [comment]
The website has been redesigned, so this has been addressed.
