### ISSUE TITLE
On smaller screens the blog posts heading text start to blend in with the photo

### ISSUE THREAD

**Issue by hamza-siddiq** [iron-fish/website#198]
On smaller screens like a mobile phone, the blog posts heading text start to blend in with the photo. I can work on a fix for this

![IMG_0748](https://user-images.githubusercontent.com/92462002/185252851-d27004d4-dc6f-40f7-841c-13273a43a804.PNG)

**Comment by dguenther** [comment]
The website has been redesigned, so this has been addressed.
