### ISSUE TITLE
Typos in website

### ISSUE THREAD

**Issue by hamza-siddiq** [iron-fish/website#201]
There are several typos currently found in the website e.g, there are misspelled words, repeated words, redundant words, misplaced words, missed words, misplaced punctuations, missed punctuations, incorrect word usage, and extra white spaces.

There are many such incidences of each and I'll fix most of them, but to save space, here are a few of them:

**Misspelled words** 
>Do not use a production bootstrap node that isn't **offically** endorsed by Iron Fish, you might end up on a malicious network.

**Repeated words** 
>It is the miner’s job however to make sure **that that** Merkle root is one that is associated with a valid tree.

**Redundant words** 
>You can use the Iron Fish Block Explorer to display information about this transaction. Of course, because Iron Fish is a fully private cryptocurrency, a limited amount of information is **actually** available to the public.

**Misplaced words** 
>And finally, **that** after all the transactions are added to the two global Merkle Trees of Notes and Nullifiers

**Missed words** 
>The Mining section describes how new blocks are constructed containing the necessary randomness for proof of work (PoW), **as well the** miners reward calculation.

**Missed punctuations**: 
>Node A broadcasts to Nodes B, C, **D and E.**

**Incorrect word usage** 
>You can read about the different accounts commands **on** this section.

**Extra white spaces** 
>At Iron Fish, we are building something we\’re truly proud of: a cryptocurrency that does not compromise on privacy or accessibility. Digital cash that embodies using privacy for **good.  We**  <- Github corrects the whitespace by default

A PR needs to fix these issues in the whole website, rather than when they are noticed. To do this I can triple-check the whole website for typos. Then triple-check the changes according to context. This might take time, but it is going to be worth it.

**Comment by dguenther** [comment]
I merged a PR to fix the typos mentioned in this issue -- I think if you'd like to make PRs to fix typos, that's fine, or if you'd like to create issues pointing out specific typos, that's fine as well, but I'd prefer not to have general issues for fixing typos, since it can be hard to tell whether the issue is closable or not.
