### ISSUE TITLE
Style errors when search by Graffiti

### ISSUE THREAD

**Issue by yuliyu123** [iron-fish/website#203]
when searching by Graffiti, the style is not friendly to look, especially rank is too high.

**Comment by hamza-siddiq** [comment]
For reference this is what @yuliyu123 means: 
<img width="1009" alt="Screen Shot 2022-08-26 at 7 54 34 PM" src="https://user-images.githubusercontent.com/92462002/186933403-8cd57abe-e71b-4555-96e6-dde028313de5.png">

I can get started and get this fixed.

**Comment by hamza-siddiq** [comment]
This should be listed in the testnet website repo. I'll add this there, and give you credit for it.

**Comment by yuliyu123** [comment]
why is the credits not updated on the leaderboard now?

**Comment by dguenther** [comment]
Closing this since a new issue was made in website-testnet.
