### ISSUE TITLE
Information about mining

### ISSUE THREAD

**Issue by cat-kitty-it** [iron-fish/website#268]
The site still contains information about mining rewards. Many people mistakenly assume that the information applies to phase three and continue to mine, creating questions as to why the rewards for this do not show up in the points.
https://ironfish.network/docs/onboarding/miner-iron-fish
![photo_2023-01-30_02-13-27](https://user-images.githubusercontent.com/108870204/215358628-de1474e1-5312-4db5-9470-b877c2efdda0.jpg)

**Comment by NullSoldier** [comment]
We'll grant this user points I fixed this in https://github.com/iron-fish/website/pull/266
